# Generated by Django 4.0.4 on 2022-06-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersappapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='username',
        ),
    ]
